apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: estap
spec:
  generators:
  - git:
      repoURL: https://github.com/alex-ykozlov-cliproj/guardium-deploy.git
      revision: HEAD
      files:
      - path: "guardium-deploy/estap/gitops/ocp-demo/**/values.yaml"
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: '{{project}}'
      source:
        chart: estap
        repoURL: https://alex-ykozlov-cliproj.github.io/Guardium_External_S-TAP/
        targetRevision: 1.0.0
        helm:
          values: |-
            {{values}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true