estap:
  db:
    host: "sqlserver02.database.windows.net"
    port: 1433
    type: "mssql"
  guardium:
    host: "20.246.81.102"
  limits:
    cpu: 500m
    memory: 756Mi
  proxy:
    debug: 0
    listen_port: 1433
  replicas: 1
  requests:
    cpu: 100m
    memory: 512Mi
  serviceAccountName: default
  fsGroup: 1000690000
  uid: 1000690000
global:
  imagePullPolicy: IfNotPresent
  dockerRegistryPrefix: "icr.io/guardium-insights"
  tag: "v11.5.3"
  secret: "estap-secret-test-02"
  secretWriterServiceAccountName: "estap-secret-writer-test-02"
